N_CALIBRATION_TRANSFORMATIONS = 9
TRAIN_SPLIT = 0.8
ORIGINAL_WINDOW_DIM = 48
PADDING_SLIDING_WINDOW = 24
CALIBRATION_THRESHOLD = 0.4

# Calibration offset vectors
X_N = [-15, 0, 15]
Y_N = [-15, 0, 15]

CLASSES = ["adult_males", "subadult_males", "adult_females", "juveniles", "pups"]

REGULARIZATION_CALIBRATION_1 = 0.001
REGULARIZATION_MULTICLASS = 0.01


NUM_NEG_SAMPLES = 1000 # Number of negative samples per image (should be >100)

PATH = ""

OVERLAPPING_THRES = 0.3

BLACK_THRESHOLD = 0.4

ARGMAX_THRESHOLD_1 = 0.3
ARGMAX_THRESHOLD_2 = 0.5
ARGMAX_THRESHOLD_3 = 0.5

EVALUATION_MARGIN = 24

